export const domains = {
  ID: {
    pname: 'id',
    lname: 'ID',
    type: 'UUID',
    notNull: true,
    default: 'gen_random_uuid()',
  },
  ID配列: {
    pname: 'id_array',
    lname: 'ID配列',
    type: 'UUID[]',
    notNull: true,
    default: "'{}'",
  },
  数: {
    pname: 'count',
    lname: '数',
    type: 'BIGINT',
    notNull: true,
    default: '0',
  },
  日時: {
    pname: 'at',
    lname: '日時',
    type: 'TIMESTAMPTZ',
    notNull: true,
    default: 'NOW()',
  },
  JSON: {
    pname: 'json',
    lname: 'JSON',
    type: 'JSONB',
    notNull: true,
    default: "'{}'",
  },
  JSON配列: {
    pname: 'json_array',
    lname: 'JSON配列',
    type: 'JSONB[]',
    notNull: true,
    default: "'{}'",
  },
  内容: {
    pname: 'content',
    lname: '内容',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { max: 10000 } },
  },
  内容配列: {
    pname: 'content_array',
    lname: '内容配列',
    type: 'TEXT[]',
    notNull: true,
    default: "'{}'",
  },
  コード: {
    pname: 'code',
    lname: 'コード',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { min: 1, max: 50 } },
  },
  コード配列: {
    pname: 'code_array',
    lname: 'コード配列',
    type: 'TEXT[]',
    notNull: true,
    default: "'{}'",
  },
  区分: {
    pname: 'kbn',
    lname: '区分',
    type: 'TEXT',
    notNull: true,
    default: "''",
  },
  区分配列: {
    pname: 'kbn_array',
    lname: '区分配列',
    type: 'TEXT[]',
    notNull: true,
    default: "'{}'",
  },
  名前: {
    pname: 'name',
    lname: '名前',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { min: 1, max: 100 } },
  },
  タイトル: {
    pname: 'title',
    lname: 'タイトル',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { min: 1, max: 200 } },
  },
  URL: {
    pname: 'url',
    lname: 'URL',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { max: 2048 } },
  },
  評価: {
    pname: 'rating',
    lname: '評価',
    type: 'BIGINT',
    notNull: true,
    default: '0',
    validation: { min: 0, max: 5 },
  },
  フラグ: {
    pname: 'flag',
    lname: 'フラグ',
    type: 'TEXT',
    notNull: true,
    default: "'false'",
  },
  説明: {
    pname: 'description',
    lname: '説明',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { max: 10000 } },
  },
  ファイル名: {
    pname: 'filename',
    lname: 'ファイル名',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { max: 255 } },
  },
  Eメール: {
    pname: 'email',
    lname: 'Eメール',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { max: 254 } },
  },
  パスワード: {
    pname: 'password',
    lname: 'パスワード',
    type: 'TEXT',
    notNull: true,
    default: "''",
    validation: { length: { min: 8, max: 128 } },
  },
} as const;

export type DomainKey = keyof typeof domains;

export type DomainToPname = {
  [K in DomainKey]: (typeof domains)[K]['pname'];
};
