DROP SCHEMA IF EXISTS source CASCADE;
DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS garbage CASCADE;

CREATE SCHEMA source;
CREATE SCHEMA public;
CREATE SCHEMA garbage;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
